

#ifndef DIO_CFG_H

#define DIO_CFG_H


/*********************************************************************/


/* Published information */
#define DIO_MODULE_ID 0x020u
#define DIO_VENDOR_ID 0x002Bu   /* vendor id of NXP */

#define DIO_AR_RELEASE_MAJOR_VERSION 0x01u
#define DIO_AR_RELEASE_MINOR_VERSION 0x00u
#define DIO_AR_RELEASE_REVISION_VERSION 0x00u

#define DIO_SW_MAJOR_VERSION 0x04u
#define DIO_SW_MINOR_VERSION 0x03u
#define DIO_SW_PATCH_VERSION 0x01u


/*********************************************************************/

/* Dio general section generated by configuration tool to enable or disable some API's and futures in Dio module*/
/* 10.1.3 */

#define DIO_DEV_ERROR_DETECT STD_ON
#define DIO_FLIP_CHANNEL_API STD_ON
#define DIO_VERSION_INFO_API STD_ON


/*********************************************************************/

/* PORT ID symbolic names for Dio_PortType */
/* 10.1.4*/

#define DioConf_PortA       0x400583FC
#define DioConf_PortB       0x400593FC
#define DioConf_PortC       0x4005A3FC
#define DioConf_PortD       0x4005B3FC
#define DioConf_PortE       0x4005C3FC
#define DioConf_PortF       0x4005D3FC

/*********************************************************************/

/* CHANNEL GROUPS ID symbolic names for Dio_ChannelGroupType */
/* 10.1.6 */

#define DIO_GROUPS_NUMBER       6

#define DioConf_PortA_Group1    (&MyDioGroupArray[0])
#define DioConf_PortB_Group1    (&MyDioGroupArray[1])
#define DioConf_PortC_Group1    (&MyDioGroupArray[2])
#define DioConf_PortD_Group1    (&MyDioGroupArray[3])
#define DioConf_PortE_Group1    (&MyDioGroupArray[4])
#define DioConf_PortF_Group1    (&MyDioGroupArray[5])



/*********************************************************************/

/* CHANNEL ID symbolic names for Dio_ChannelType*/
/* 10.1.5*/

#define DioConf_Channel_0       0x40058004
#define DioConf_Channel_1       0x40058008
#define DioConf_Channel_2       0x40058010
#define DioConf_Channel_3       0x40058020
#define DioConf_Channel_4       0x40058040
#define DioConf_Channel_5       0x40058080
#define DioConf_Channel_6       0x40058100
#define DioConf_Channel_7       0x40058200

#define DioConf_Channel_8       0x40059004
#define DioConf_Channel_9       0x40059008
#define DioConf_Channel_10      0x40059010
#define DioConf_Channel_11      0x40059020
#define DioConf_Channel_12      0x40059040
#define DioConf_Channel_13      0x40059080
#define DioConf_Channel_14      0x40059100
#define DioConf_Channel_15      0x40059200

#define DioConf_Channel_16      0x4005A004
#define DioConf_Channel_17      0x4005A008
#define DioConf_Channel_18      0x4005A010
#define DioConf_Channel_19      0x4005A020
#define DioConf_Channel_20      0x4005A040
#define DioConf_Channel_21      0x4005A080
#define DioConf_Channel_22      0x4005A100
#define DioConf_Channel_23      0x4005A200

#define DioConf_Channel_24      0x4005B004
#define DioConf_Channel_25      0x4005B008
#define DioConf_Channel_26      0x4005B010
#define DioConf_Channel_27      0x4005B020
#define DioConf_Channel_28      0x4005B040
#define DioConf_Channel_29      0x4005B080
#define DioConf_Channel_30      0x4005B100
#define DioConf_Channel_31      0x4005B200

#define DioConf_Channel_32      0x4005C004
#define DioConf_Channel_33      0x4005C008
#define DioConf_Channel_34      0x4005C010
#define DioConf_Channel_35      0x4005C020
#define DioConf_Channel_36      0x4005C040
#define DioConf_Channel_37      0x4005C080

#define DioConf_Channel_38      0x4005D004
#define DioConf_Channel_39      0x4005D008
#define DioConf_Channel_40      0x4005D010
#define DioConf_Channel_41      0x4005D020
#define DioConf_Channel_42      0x4005D040

/*********************************************************************/



#endif
