/*
 * Mcu_Cfg.h
 *
 *  Created on: Nov 19, 2019
 *  Author: Bebo
 *  AUTOSAR Version: 4.3.1
 *  DOC Name: AUTOSAR_SWS_MCUDriver.pdf
 *  Target:  ARM TivaC TM4C123GH6PM
 *
 */

#ifndef MCU_CFG_H_
#define MCU_CFG_H_

/*********************************************************************/


/* Published information */
#define MCU_MODULE_ID 30u
#define MCU_VENDOR_ID 0x002Bu   /* vendor id of NXP */

#define MCU_AR_RELEASE_MAJOR_VERSION 0x01u
#define MCU_AR_RELEASE_MINOR_VERSION 0x00u
#define MCU_AR_RELEASE_REVISION_VERSION 0x00u

#define MCU_SW_MAJOR_VERSION 0x04u
#define MCU_SW_MINOR_VERSION 0x03u
#define MCU_SW_PATCH_VERSION 0x01u

/*********************************************************************/





/* MCU section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.1 */
/************************************************************************************************/
/* McuGeneralConfiguration section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.2 */

#define MCU_DEV_ERROR_DETECT    STD_ON
#define MCU_GET_RAM_STATE_API   STD_ON
#define MCU_NO_PLL              STD_OFF
#define MCU_INIT_CLOCK          STD_ON
#define MCU_PERFORM_RESET_API   STD_ON
#define MCU_VERSION_INFO_API    STD_ON


/************************************************************************************************/
/* McuModuleConfiguration section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.3 */

/* if reset type element in configuration structure has the same value reset will be performed */
#define MCU_RESET_SETTING   0xFF

/******************************************************************/
/* McuClockSettingConfig section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.4 */
#define McuConf_ClockSetting_1  0x00u
#define McuConf_ClockSetting_2  0x01u

/************************************************/
/* McuClockSettingConfig section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.8 */
/* post build configuration */
/************************************************/
/******************************************************************/
/* McuDemEventParameterRefs section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.5 */

/******************************************************************/
/* McuModeSettingConf section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.6 */

#define McuConf_SleepMode 0x00u
#define McuConf_DeepSleepMode 0x01u


/******************************************************************/
/* McuRamSectorSettingConf section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.7 */

/******************************************************************/
/************************************************************************************************/
/* McuPublishedInformation section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.9 */
/******************************************************************/
/* McuResetReasonConf section generated by configuration tool to enable or disable some API's and futures in MCU module*/
/* 10.2.10 */

#define McuConf_ExternalReset       0x01u
#define McuConf_PowerOnReset        0x02u
#define McuConf_BrownOutReset       0x04u
#define McuConf_Watchdog_0_Reset    0x08u
#define McuConf_SoftwareReset       0x10u
#define McuConf_Watchdog_1_Reset    0x20u
#define McuConf_MOSC_Fail           0x00010000u

/******************************************************************/

#define MCU_CONFIGURATION_SETTING_NUMBER 1
#define MCU_MAX_CLOCK_SETTING_NUMBER 2
#define MCU_MAX_RAM_SECTOR_NUMBER 2

/************************************************************************************************/


#endif /* MCU_CFG_H_ */
